export const ACTIVE_SEMESTER_CHANGE = 'ACTIVE_SEMESTER_CHANGE';

export const ADD_STATUS_FILTER = 'ADD_STATUS_FILTER';
export const REMOVE_STATUS_FILTER = 'REMOVE_STATUS_FILTER';

export const ADD_COURSE_FILTER = 'ADD_COURSE_FILTER';
export const REMOVE_COURSE_FILTER = 'REMOVE_COURSE_FILTER';